#!/bin/sh

theme=$1
config="/root/.config/termite/config"
config_nocolor="/root/.config/termite/configs/config1"

if [ -z "$theme" ]; then
	printf "Please select a theme. Use 'list' option to list the themes\n"
elif [ "$theme" = "list" ]; then
	cd "/root/.config/termite/configs/themes" && ls
elif [ "$theme" = "edit" ]; then
	vim "/root/.config/termite/configs/themes/$2"
elif [ "$theme" = "reload" ]; then
	killall -USR1 termite
else
	cat "/root/.config/termite/configs/themes/$theme" > $config
	printf "\n" >> $config
	cat $config_nocolor >> $config

	killall -USR1 termite
	printf "Selected theme: $theme\n"
fi
